ragbot:
  chunker-config:
    max-chunk-size: 800
    overlap-size: 100

  chat-llm:
    model: gpt-4.1-mini
    temperature: 0.0

  persona: clause
  objective: legal


embabel:
  agent:
    shell:
      # When you start chat, redirect log to file
      redirect-log-to-file: true


